config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'

  get 'contacts/create'

  get 'contacts/delete'

  get 'contacts/update'

  root 'landings#index'

  

  resources :users do
    resources :contact_lists do
      resources :contacts
    end
  end

  get '/sessions/new' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/sessions' => 'sessions#delete'

  get '/users/:user_id/contact_lists/:contact_list_id/calls' => 'twilio#call', as: 'twilio_calls'

  post '/users/:user_id/verify_number' => 'twilio#verify_number', as: 'verify_number'

  post '/check_verification' => 'twilio#verification_status', as: 'verification_status'

  post 'connect' => 'twilio#connect'

  match 'ivr/welcome' => 'twilio#ivr_welcome', via: [:get, :post], as: 'welcome'

  match 'ivr/selection' => 'twilio#menu_selection', via: [:get, :post], as: 'menu'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :contact_lists
	has_many :contacts, through: :contact_lists

	validates :email, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def show
		@user = current_user
	end

	# TODO: Uncommet code below when you fix the particular account issue
	# def create
	# 	@user = User.new(user_params.merge(user_number))
	# 	if @user.save
	# 		redirect_to '/'
	# 	else
	# 		@errors = @user.errors.full_messages
	# 		render 'new'
	# 	end
	# end



	private
	def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

	def user_phone
		params.require(:phone).permit(:area, :pre, :body)
	end

	def user_number
		{number: "#{user_phone[:area]}#{user_phone[:pre]}#{user_phone[:body]}"}
	end

end

app/views/users/_form.html.erb
<div class="row landing-body">
    <div class="col-sm-6 login-div">
      <div class="panel-body">
				<div class="panel-heading clearfix">
					<h1 class="panel-title">Registracion</h1>
          <%if @errors.present?%>
            <ul>
              <%@errors.each do |error|%>
                <li><%=error%></li>
              <%end%>
            </ul>
          <%end%>
					<%= form_for(@user, :html =>{ :role => "form"}) do |f| %>
						<div class="form-group">
							<%= label_tag "Nombre", nil, :class=>"fsr-only" %>
							<%= f.text_field :first_name, placeholder: "Nombre..." ,:class=> "form-control" %>
						</div>

						<div class="form-group">
							<%= label_tag "Apellido", nil, :class=>"fsr-only" %>
							<%= f.text_field :last_name, placeholder: "Apellido..." ,:class=> "form-control" %>
						</div>

						<div class="form-group">
							<%= label_tag "Correo Electronico", nil, :class=>"fsr-only" %>
							<%= f.text_field :email, placeholder: "Email" ,:class=> "form-control" %>
						</div>

						<div class="form-group" style="margin-left: -1em;">
							<%= label_tag "Numero Telephonico", nil, :class=>"fsr-only number-input" %>
							<div class="form-group">
								<div class="col-xs-3">
									<input type="tel" name="phone[area]" class="form-control"  size="3" maxlength="3" required="required" placeholder="XXX" title="Area">
								</div>

								<div class="col-xs-3">
									<input type="tel" name="phone[pre]" class="form-control" size="3" maxlength="3" required="required" placeholder="XXX" title="">
								</div>
								<div class="col-xs-3">
									<input type="tel" name="phone[body]" class="form-control" size="4" maxlength="4" required="required" placeholder="XXXX" title="">
								</div>
							</div>
						</div><br><br>

						<div class="form-group">
							<%= label_tag "Contraseña", nil, :class=>"fsr-only" %>
							<%= f.password_field :password, placeholder: "********",:class=> "form-control"  %>
						</div>
						<%= f.submit "Registrar", :class => "btn btn-warning"  %>
					<% end %>
	    </div>
	  </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container contact-div-container">
  <%if current_user.verified == false %>
    <div class="row pull-right">
      <div class="col-lg-12 ">
        <button id="<%=@user.id%>" class="btn btn-warning btn-lg varify-phone-button" data-toggle="modal" data-target="#myModalHorizontal">
        Verifique Su Numero
        </button>
        <!-- Modal -->
        <div class="modal fade" id="myModalHorizontal" tabindex="-1" role="dialog"aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
            <!-- Modal Header -->
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                Ingrese El siguiente Numero:
                </h4>
              </div>
              <!-- Modal Body -->
              <div class="modal-body">
                <div class="form-group">
                  <!-- <h3>Numero: </h3> -->
                  <h2 class="center-text" id="twilio-verification-code"> 5643</h2>
                </div>
              </div>
              <!-- Modal Footer -->
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>


<div class="container">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title"><%= current_user.first_name%> <%=current_user.last_name%></h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="https://cdn0.iconfinder.com/data/icons/PRACTIKA/256/user.png" class="img-circle img-responsive"> </div>
                <div class=" col-md-9 col-lg-9 ">
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>Correo:</td>
                        <td><%= current_user.email%></td>
                      </tr>
                      <tr>
                        <td>Numero:</td>
                        <td><%= current_user.number %></td>
                      </tr>
                      <tr>
                        <td>Numero Verificado:</td>
                        <td><%= current_user.verified_number %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
             <div class="panel-footer">
               <a href="/users/<%=current_user.id%>/contact_lists" data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><span class="glyphicon glyphicon-pencil"></span> Mis Contactos</a>
               <!-- <span class="pull-right">
                 <a href="edit.html" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i> Editar</a>
               </span> -->
            </div>
          </div>
          <%= link_to "Iniciar Llamadas", contacts_new_path(current_user.id), :class => "btn btn-success btn-new-contacts" %>
        </div>
      </div>
    </div>