config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'

  get 'contacts/create'

  get 'contacts/delete'

  get 'contacts/update'

  root 'landings#index'

  

  resources :users do
    resources :contact_lists do
      resources :contacts
    end
  end

  get '/sessions/new' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/sessions' => 'sessions#delete'

  get '/users/:user_id/contact_lists/:contact_list_id/calls' => 'twilio#call', as: 'twilio_calls'

  post '/users/:user_id/verify_number' => 'twilio#verify_number', as: 'verify_number'

  post '/check_verification' => 'twilio#verification_status', as: 'verification_status'

  post 'connect' => 'twilio#connect'

  match 'ivr/welcome' => 'twilio#ivr_welcome', via: [:get, :post], as: 'welcome'

  match 'ivr/selection' => 'twilio#menu_selection', via: [:get, :post], as: 'menu'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebTeleMarketing</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
    	<div class="navbar navbar-inverse" role="navigation">
    		<div class="container">
    			<div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Navigation</span>
            <span class="icon-bar">1</span>
            <span class="icon-bar">2</span>
            <span class="icon-bar">3</span>
          </button>
    				<a class="navbar-brand" href="/">Web-TeleMarketer</a>
    			</div>
    			<div>
    				<ul class="nav navbar-nav navbar-right">
    					<li class="active"> <a href="/">Home</a></li>
    					<%if current_user%>
                <!-- <li><%=  link_to "Acerca", root_path%></li> -->
    						<li class="dropdown">
    							<a class="dropdown-toggle" data-toggle="dropdown" href="#"> <%=current_user.first_name%> <span></spam></a>
    							<ul class="dropdown-menu">
                    <li><%=  link_to "Contactos",  user_contact_lists_path(current_user.id)%></li>
    								<li> <a href="/">Mis Clientes</a></li>
                    <li><%=  link_to "<small><span class='glyphicon glyphicon-off'></span></small> salir".html_safe,sessions_path, method: "delete"%></li>
    							</ul>
    						</li>
    						<%else%>
                <!-- <li><%=  link_to "Igresar", sessions_new_path%></li> -->
    						<!-- <li><%=link_to "Registrar", new_user_path %></li> -->
    					<% end%>
    				</ul>
    			</div>
    		</div>
    	</div>
    </header>
    <div class="container">
    	<%= yield %>
    </div>
    <!-- <div class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
      <div class="container">
        <div class="navbar-text pull-center">
          <p>
            © 2016  Web-TeleMarketer
          </p>
        </div>
      </div>
    </div> -->
  </body>
</html>